services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: arthur
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meu_banco_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
